# Generated by Django 2.1.7 on 2022-02-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_class', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mssv', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=False)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcam.Class')),
            ],
        ),
        migrations.AddField(
            model_name='authentication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcam.Student'),
        ),
    ]
